INSERT INTO SPI_OWNER.RECORRENCIA_AUTORIZACAO_CICLO (
    OID_RECORRENCIA_AUTORIZACAO_CICLO,
    OID_RECORRENCIA_AUTORIZACAO,
    TPO_STATUS,
    DAT_INICIAL,
    DAT_FINAL,
    DAT_CRIACAO_REGISTRO,
    DAT_ALTERACAO_REGISTRO
) VALUES (
    12345, -- OID_RECORRENCIA_AUTORIZACAO_CICLO
    99999, -- OID_RECORRENCIA_AUTORIZACAO
    'ENCERRADO', -- TPO_STATUS
    DATE '2025-05-01', -- DAT_INICIAL
    DATE '2025-05-07', -- DAT_FINAL
    CURRENT_TIMESTAMP, -- DAT_CRIACAO_REGISTRO
    CURRENT_TIMESTAMP -- DAT_ALTERACAO_REGISTRO
);
INSERT INTO SPI_OWNER.RECORRENCIA_AUTORIZACAO_CICLO (
    OID_RECORRENCIA_AUTORIZACAO_CICLO,
    OID_RECORRENCIA_AUTORIZACAO,
    TPO_STATUS,
    DAT_INICIAL,
    DAT_FINAL,
    DAT_CRIACAO_REGISTRO,
    DAT_ALTERACAO_REGISTRO
) VALUES (
    12346, -- OID_RECORRENCIA_AUTORIZACAO_CICLO
    99999, -- OID_RECORRENCIA_AUTORIZACAO
    'ABERTO', -- TPO_STATUS
    DATE '2025-05-08', -- DAT_INICIAL
    DATE '2025-05-14', -- DAT_FINAL
    CURRENT_TIMESTAMP, -- DAT_CRIACAO_REGISTRO
    CURRENT_TIMESTAMP -- DAT_ALTERACAO_REGISTRO
);
INSERT INTO SPI_OWNER.RECORRENCIA_AUTORIZACAO_CICLO (
    OID_RECORRENCIA_AUTORIZACAO_CICLO,
    OID_RECORRENCIA_AUTORIZACAO,
    TPO_STATUS,
    DAT_INICIAL,
    DAT_FINAL,
    DAT_CRIACAO_REGISTRO,
    DAT_ALTERACAO_REGISTRO
) VALUES (
    12347, -- OID_RECORRENCIA_AUTORIZACAO_CICLO
    99999, -- OID_RECORRENCIA_AUTORIZACAO
    'ABERTO', -- TPO_STATUS
    DATE '2025-05-15', -- DAT_INICIAL
    DATE '2025-05-21', -- DAT_FINAL
    CURRENT_TIMESTAMP, -- DAT_CRIACAO_REGISTRO
    CURRENT_TIMESTAMP -- DAT_ALTERACAO_REGISTRO
);
-- Ciclos autorizacao que permite retentativa APOS VENCIMENTO
INSERT INTO SPI_OWNER.RECORRENCIA_AUTORIZACAO_CICLO (
    OID_RECORRENCIA_AUTORIZACAO_CICLO,
    OID_RECORRENCIA_AUTORIZACAO,
    TPO_STATUS,
    DAT_INICIAL,
    DAT_FINAL,
    DAT_CRIACAO_REGISTRO,
    DAT_ALTERACAO_REGISTRO
) VALUES (
    22346, -- OID_RECORRENCIA_AUTORIZACAO_CICLO
    99998, -- OID_RECORRENCIA_AUTORIZACAO
    'ABERTO', -- TPO_STATUS
    DATE '2025-05-08', -- DAT_INICIAL
    DATE '2025-05-14', -- DAT_FINAL
    CURRENT_TIMESTAMP, -- DAT_CRIACAO_REGISTRO
    CURRENT_TIMESTAMP -- DAT_ALTERACAO_REGISTRO
);
INSERT INTO SPI_OWNER.RECORRENCIA_AUTORIZACAO_CICLO (
    OID_RECORRENCIA_AUTORIZACAO_CICLO,
    OID_RECORRENCIA_AUTORIZACAO,
    TPO_STATUS,
    DAT_INICIAL,
    DAT_FINAL,
    DAT_CRIACAO_REGISTRO,
    DAT_ALTERACAO_REGISTRO
) VALUES (
    22347, -- OID_RECORRENCIA_AUTORIZACAO_CICLO
    99998, -- OID_RECORRENCIA_AUTORIZACAO
    'ABERTO', -- TPO_STATUS
    DATE '2025-05-15', -- DAT_INICIAL
    DATE '2025-05-21', -- DAT_FINAL
    CURRENT_TIMESTAMP, -- DAT_CRIACAO_REGISTRO
    CURRENT_TIMESTAMP -- DAT_ALTERACAO_REGISTRO
);