-- Autorização com ciclos que permite AGENDAMENTO
INSERT INTO SPI_OWNER.RECORRENCIA_AUTORIZACAO (
    OID_RECORRENCIA_AUTORIZACAO,
    ID_RECORRENCIA,
    ID_INFORMACAO_STATUS_ENVIO,
    ID_INFORMACAO_STATUS_RECEBIMENTO,
    TPO_JORNADA,
    TPO_STATUS,
    TPO_SUB_STATUS,
    TPO_FREQUENCIA,
    FLG_PERMITE_LINHA_CREDITO,
    FLG_PERMITE_RETENTATIVA,
    FLG_PERMITE_NOTIFICACAO_AGENDAMENTO,
    NUM_CPF_CNPJ_PAGADOR,
    TXT_NOME_PAGADOR,
    NUM_AGENCIA_PAGADOR,
    NUM_CONTA_PAGADOR,
    NUM_INSTITUICAO_PAGADOR,
    COD_POSTO_PAGADOR,
    TPO_CONTA_PAGADOR,
    TPO_PESSOA_PAGADOR,
    TPO_SISTEMA_PAGADOR,
    TPO_CANAL_PAGADOR,
    TXT_NOME_RECEBEDOR,
    NUM_INSTITUICAO_RECEBEDOR,
    NUM_CPF_CNPJ_RECEBEDOR,
    TXT_NOME_DEVEDOR,
    NUM_CPF_CNPJ_DEVEDOR,
    TXT_DESCRICAO,
    NUM_CONTRATO,
    COD_MUN_IBGE,
    NUM_VALOR_MAXIMO,
    DAT_INICIAL_RECORRENCIA,
    DAT_INICIO_CONFIRMACAO,
    DAT_FINAL_RECORRENCIA,
    DAT_CRIACAO_RECORRENCIA,
    DAT_CRIACAO_REGISTRO,
    DAT_ALTERACAO_REGISTRO
) VALUES (
    99999, -- OID_RECORRENCIA_AUTORIZACAO
    'RN1234567890123456789012345', -- ID_RECORRENCIA
    'IS1234567890123456789012345', -- ID_INFORMACAO_STATUS_ENVIO
    NULL, -- ID_INFORMACAO_STATUS_RECEBIMENTO
    'JORNADA_1', -- TPO_JORNADA
    'APROVADA', -- TPO_STATUS
    NULL, -- TPO_SUB_STATUS
    'SEMANAL', -- TPO_FREQUENCIA
    'S', -- FLG_PERMITE_LINHA_CREDITO
    'N', -- FLG_PERMITE_RETENTATIVA
    'S', -- FLG_PERMITE_NOTIFICACAO_AGENDAMENTO
    '12345678901', -- NUM_CPF_CNPJ_PAGADOR
    'João Silva', -- TXT_NOME_PAGADOR
    '1234', -- NUM_AGENCIA_PAGADOR
    '567890', -- NUM_CONTA_PAGADOR
    '0001', -- NUM_INSTITUICAO_PAGADOR
    '0012', -- COD_POSTO_PAGADOR
    'CORRENTE', -- TPO_CONTA_PAGADOR
    'PF', -- TPO_PESSOA_PAGADOR
    'LEGADO', -- TPO_SISTEMA_PAGADOR
    'MOBI', -- TPO_CANAL_PAGADOR
    'Empresa XYZ Ltda', -- TXT_NOME_RECEBEDOR
    '0002', -- NUM_INSTITUICAO_RECEBEDOR
    '98765432100', -- NUM_CPF_CNPJ_RECEBEDOR
    'Maria Oliveira', -- TXT_NOME_DEVEDOR
    '12345678909', -- NUM_CPF_CNPJ_DEVEDOR
    'Pagamento mensal', -- TXT_DESCRICAO
    'CONTRATO123', -- NUM_CONTRATO
    '4314902', -- COD_MUN_IBGE
    1000.00, -- NUM_VALOR_MAXIMO
    DATE '2025-05-01', -- DAT_INICIAL_RECORRENCIA
    TIMESTAMP '2025-01-01 10:00:00', -- DAT_INICIO_CONFIRMACAO
    DATE '2025-12-31', -- DAT_FINAL_RECORRENCIA
    TIMESTAMP '2025-01-02 09:00:00', -- DAT_CRIACAO_RECORRENCIA
    CURRENT_TIMESTAMP, -- DAT_CRIACAO_REGISTRO
    CURRENT_TIMESTAMP -- DAT_ALTERACAO_REGISTRO
);

-- Autorização com ciclos que permite RETENTATIVA APOS VENCIMENTO
INSERT INTO SPI_OWNER.RECORRENCIA_AUTORIZACAO (
    OID_RECORRENCIA_AUTORIZACAO,
    ID_RECORRENCIA,
    ID_INFORMACAO_STATUS_ENVIO,
    ID_INFORMACAO_STATUS_RECEBIMENTO,
    TPO_JORNADA,
    TPO_STATUS,
    TPO_SUB_STATUS,
    TPO_FREQUENCIA,
    FLG_PERMITE_LINHA_CREDITO,
    FLG_PERMITE_RETENTATIVA,
    FLG_PERMITE_NOTIFICACAO_AGENDAMENTO,
    NUM_CPF_CNPJ_PAGADOR,
    TXT_NOME_PAGADOR,
    NUM_AGENCIA_PAGADOR,
    NUM_CONTA_PAGADOR,
    NUM_INSTITUICAO_PAGADOR,
    COD_POSTO_PAGADOR,
    TPO_CONTA_PAGADOR,
    TPO_PESSOA_PAGADOR,
    TPO_SISTEMA_PAGADOR,
    TPO_CANAL_PAGADOR,
    TXT_NOME_RECEBEDOR,
    NUM_INSTITUICAO_RECEBEDOR,
    NUM_CPF_CNPJ_RECEBEDOR,
    TXT_NOME_DEVEDOR,
    NUM_CPF_CNPJ_DEVEDOR,
    TXT_DESCRICAO,
    NUM_CONTRATO,
    COD_MUN_IBGE,
    NUM_VALOR_MAXIMO,
    DAT_INICIAL_RECORRENCIA,
    DAT_INICIO_CONFIRMACAO,
    DAT_FINAL_RECORRENCIA,
    DAT_CRIACAO_RECORRENCIA,
    DAT_CRIACAO_REGISTRO,
    DAT_ALTERACAO_REGISTRO
) VALUES (
    99998, -- OID_RECORRENCIA_AUTORIZACAO
    'RR1234567890123456789012345', -- ID_RECORRENCIA
    'IS1234567890123456789012345', -- ID_INFORMACAO_STATUS_ENVIO
    NULL, -- ID_INFORMACAO_STATUS_RECEBIMENTO
    'JORNADA_1', -- TPO_JORNADA
    'APROVADA', -- TPO_STATUS
    NULL, -- TPO_SUB_STATUS
    'SEMANAL', -- TPO_FREQUENCIA
    'S', -- FLG_PERMITE_LINHA_CREDITO
    'S', -- FLG_PERMITE_RETENTATIVA
    'S', -- FLG_PERMITE_NOTIFICACAO_AGENDAMENTO
    '12345678901', -- NUM_CPF_CNPJ_PAGADOR
    'João Silva', -- TXT_NOME_PAGADOR
    '1234', -- NUM_AGENCIA_PAGADOR
    '567890', -- NUM_CONTA_PAGADOR
    '0001', -- NUM_INSTITUICAO_PAGADOR
    '0012', -- COD_POSTO_PAGADOR
    'CORRENTE', -- TPO_CONTA_PAGADOR
    'PF', -- TPO_PESSOA_PAGADOR
    'LEGADO', -- TPO_SISTEMA_PAGADOR
    'MOBI', -- TPO_CANAL_PAGADOR
    'Empresa XYZ Ltda', -- TXT_NOME_RECEBEDOR
    '0002', -- NUM_INSTITUICAO_RECEBEDOR
    '98765432100', -- NUM_CPF_CNPJ_RECEBEDOR
    'Maria Oliveira', -- TXT_NOME_DEVEDOR
    '12345678909', -- NUM_CPF_CNPJ_DEVEDOR
    'Pagamento mensal', -- TXT_DESCRICAO
    'CONTRATO123', -- NUM_CONTRATO
    '4314902', -- COD_MUN_IBGE
    1000.00, -- NUM_VALOR_MAXIMO
    DATE '2025-05-01', -- DAT_INICIAL_RECORRENCIA
    TIMESTAMP '2025-01-01 10:00:00', -- DAT_INICIO_CONFIRMACAO
    DATE '2025-12-31', -- DAT_FINAL_RECORRENCIA
    TIMESTAMP '2025-01-02 09:00:00', -- DAT_CRIACAO_RECORRENCIA
    CURRENT_TIMESTAMP, -- DAT_CRIACAO_REGISTRO
    CURRENT_TIMESTAMP -- DAT_ALTERACAO_REGISTRO
);