-- INSTRUCAO COM DADOS INVALIDOS COM OBJETIVO DE NEGAR PEDIDOS
INSERT INTO SPI_OWNER.RECORRENCIA_INSTRUCAO_PAGAMENTO (
    COD_FIM_A_FIM,
    OID_RECORRENCIA_AUTORIZACAO_CICLO,
    OID_RECORRENCIA_AUTORIZACAO,
    ID_RECORRENCIA,
    NUM_CPF_CNPJ_PAGADOR,
    NUM_INSTITUICAO_PAGADOR,
    TXT_NOME_DEVEDOR,
    NUM_CPF_CNPJ_DEVEDOR,
    NUM_VALOR,
    NUM_CPF_CNPJ_RECEBEDOR,
    NUM_AGENCIA_RECEBEDOR,
    NUM_CONTA_RECEBEDOR,
    NUM_INSTITUICAO_RECEBEDOR,
    TPO_CONTA_RECEBEDOR,
    ID_CONCILIACAO_RECEBEDOR,
    TPO_STATUS,
    TPO_SUB_STATUS,
    TPO_FINALIDADE_AGENDAMENTO,
    TXT_INFORMACOES_ENTRE_USUARIOS,
    COD_MOTIVO_REJEICAO,
    DAT_VENCIMENTO,
    DAT_CONFIRMACAO,
    DAT_EMISSAO,
    DAT_CONCLUIDO,
    DAT_CRIACAO_REGISTRO,
    DAT_ALTERACAO_REGISTRO
) VALUES (
    'FIM1234567890123456789012345678', -- COD_FIM_A_FIM --
    22347, -- OID_RECORRENCIA_AUTORIZACAO_CICLO
    99998, -- OID_RECORRENCIA_AUTORIZACAO
    'RN1234567890123456789012345', -- ID_RECORRENCIA
    '12345678901', -- NUM_CPF_CNPJ_PAGADOR
    '0001', -- NUM_INSTITUICAO_PAGADOR
    'Maria Oliveira', -- TXT_NOME_DEVEDOR
    '12345678909', -- NUM_CPF_CNPJ_DEVEDOR
    500.00, -- NUM_VALOR
    '98765432100', -- NUM_CPF_CNPJ_RECEBEDOR
    '1234', -- NUM_AGENCIA_RECEBEDOR
    '567890', -- NUM_CONTA_RECEBEDOR
    '0002', -- NUM_INSTITUICAO_RECEBEDOR
    'CORRENTE', -- TPO_CONTA_RECEBEDOR
    'CONCILIACAO123', -- ID_CONCILIACAO_RECEBEDOR
    'CANCELADA', -- TPO_STATUS
    NULL, -- TPO_SUB_STATUS
    'AGENDADO', -- TPO_FINALIDADE_AGENDAMENTO
    'Informações adicionais', -- TXT_INFORMACOES_ENTRE_USUARIOS
    'STATUS_RECORRENCIA_DIFERENTE_CFDB_CONFIRMADO_USUARIO_PAGADOR', -- COD_MOTIVO_REJEICAO
    DATE '2025-05-15', -- DAT_VENCIMENTO
    NULL, -- DAT_CONFIRMACAO
    TIMESTAMP '2025-05-15 10:00:00', -- DAT_EMISSAO
    NULL, -- DAT_CONCLUIDO
    CURRENT_TIMESTAMP, -- DAT_CRIACAO_REGISTRO
    CURRENT_TIMESTAMP -- DAT_ALTERACAO_REGISTRO
);