-- Titular Principal --
INSERT INTO SPI_OWNER.RECORRENCIA_PAGADOR (OID_RECORRENCIA_PAGADOR, NUM_CPF_CNPJ, NOME, NUM_AGENCIA, NUM_CONTA,
                                           NUM_INSTITUICAO, COD_POSTO, TPO_CONTA, TPO_PESSOA)
VALUES (1, '24110287000170', 'Adelia Maria Moschem Colorio', '0101', '000023', '99999004', '19', 'CONTA_CORRENTE',
        'PJ');

-- Titular Secundário --
INSERT INTO SPI_OWNER.RECORRENCIA_PAGADOR (OID_RECORRENCIA_PAGADOR, NUM_CPF_CNPJ, NOME, NUM_AGENCIA, NUM_CONTA,
                                           NUM_INSTITUICAO, COD_POSTO, TPO_CONTA, TPO_PESSOA)
VALUES (2, '28574109053', 'Alzileide Marya Silveira', '0101', '000023', '99999004', '19', 'CONTA_CORRENTE',
        'PF');

-- Recebedor --
INSERT INTO SPI_OWNER.RECORRENCIA_RECEBEDOR (OID_RECORRENCIA_RECEBEDOR, NUM_CPF_CNPJ, NOME, NUM_AGENCIA, NUM_CONTA,
                                             NUM_INSTITUICAO, TPO_CONTA, TPO_PESSOA, TPO_CHAVE, CHAVE)
VALUES (1, '12345678901', 'Nome Fictício', '1234', '567890', '0001', 'CONTA_CORRENTE', 'PF', 'EMAIL',
        'email@exemplo.com');

-- Recorrencias Titular Principal --
INSERT INTO SPI_OWNER.RECORRENCIA (OID_RECORRENCIA, OID_RECORRENCIA_PAGADOR, OID_RECORRENCIA_RECEBEDOR, ID_RECORRENCIA,
                                   TPO_RECORRENCIA, NOME, TPO_CANAL, TPO_ORIGEM_SISTEMA, TPO_INICIACAO, TPO_STATUS,
                                   TPO_INICIACAO_CANAL, TPO_FREQUENCIA, NUM_INIC_CNPJ, DAT_CRIACAO)
VALUES (1, 1, 1, '9274fe63-bda7-4026-8684-0c199e8fc7f1', 'AGENDADO', 'Recorrência Fictícia', 'MOBI', 'LEGADO',
        'PIX_PAYMENT_BY_KEY', 'CRIADO', 'CHAVE', 'MENSAL', '12345678901234', TIMESTAMP '2025-02-03 10:54:33.000000');
INSERT INTO SPI_OWNER.RECORRENCIA_TRANSACAO (OID_RECORRENCIA_TRANSACAO, OID_RECORRENCIA, ID_PARCELA,
                                             TPO_MOTIVO_EXCLUSAO, TPO_STATUS, COD_FIM_A_FIM, NUM_VALOR,
                                             FLG_NOTIFICACAO_DIA_ANTERIOR, INFORMACOES_ENTRE_USUARIOS,
                                             ID_CONCILIACAO_RECEBEDOR, DAT_TRANSACAO, DAT_EXCLUSAO)
VALUES (1, 1, '30d98f8b-791c-4a9e-8b1e-c519bd01af2c', null, 'CRIADO', null, 100.00, 'S',
        null, null, ADD_MONTHS(SYSDATE, 1), null);

-- Recorrências Titular Secundário --
INSERT INTO SPI_OWNER.RECORRENCIA (OID_RECORRENCIA, OID_RECORRENCIA_PAGADOR, OID_RECORRENCIA_RECEBEDOR, ID_RECORRENCIA,
                                   TPO_RECORRENCIA, NOME, TPO_CANAL, TPO_ORIGEM_SISTEMA, TPO_INICIACAO, TPO_STATUS,
                                   TPO_INICIACAO_CANAL, TPO_FREQUENCIA, NUM_INIC_CNPJ, DAT_CRIACAO)
VALUES (2, 2, 1, '2f335153-4d6a-4af1-92a0-c52c5c827af9', 'AGENDADO', 'Recorrência Fictícia', 'MOBI', 'LEGADO',
        'PIX_PAYMENT_BY_KEY', 'CRIADO', 'CHAVE', 'MENSAL', '12345678901234', TIMESTAMP '2025-02-03 10:54:33.000000');
INSERT INTO SPI_OWNER.RECORRENCIA_TRANSACAO (OID_RECORRENCIA_TRANSACAO, OID_RECORRENCIA, ID_PARCELA,
                                             TPO_MOTIVO_EXCLUSAO, TPO_STATUS, COD_FIM_A_FIM, NUM_VALOR,
                                             FLG_NOTIFICACAO_DIA_ANTERIOR, INFORMACOES_ENTRE_USUARIOS,
                                             ID_CONCILIACAO_RECEBEDOR, DAT_TRANSACAO, DAT_EXCLUSAO)
VALUES (2, 2, '3df10a73-a1de-4486-8a93-224cbea1f862', null, 'CONCLUIDO', 'E9999900420250211105433kYYIqIERL', 10.00, 'S',
        null, null, ADD_MONTHS(SYSDATE, -3), null);

INSERT INTO SPI_OWNER.RECORRENCIA_TRANSACAO (OID_RECORRENCIA_TRANSACAO, OID_RECORRENCIA, ID_PARCELA,
                                             TPO_MOTIVO_EXCLUSAO, TPO_STATUS, COD_FIM_A_FIM, NUM_VALOR,
                                             FLG_NOTIFICACAO_DIA_ANTERIOR, INFORMACOES_ENTRE_USUARIOS,
                                             ID_CONCILIACAO_RECEBEDOR, DAT_TRANSACAO, DAT_EXCLUSAO)
VALUES (3, 2, '87cbc878-6f33-40cf-87d3-7670a09ca8b5', null, 'CONCLUIDO', 'E9999900420250211105433kYYIqIERa', 10.00, 'S',
        null, null, ADD_MONTHS(SYSDATE, -2), null);

INSERT INTO SPI_OWNER.RECORRENCIA_TRANSACAO (OID_RECORRENCIA_TRANSACAO, OID_RECORRENCIA, ID_PARCELA,
                                             TPO_MOTIVO_EXCLUSAO, TPO_STATUS, COD_FIM_A_FIM, NUM_VALOR,
                                             FLG_NOTIFICACAO_DIA_ANTERIOR, INFORMACOES_ENTRE_USUARIOS,
                                             ID_CONCILIACAO_RECEBEDOR, DAT_TRANSACAO, DAT_EXCLUSAO)
VALUES (4, 2, '77e56520-0cb4-49ab-a82e-26d57ad22e65', null, 'EXCLUIDO', 'E9999900420250211105433kYYIqIERb', 10.00, 'S',
        null, null, ADD_MONTHS(SYSDATE, -1), null);

INSERT INTO SPI_OWNER.RECORRENCIA_TRANSACAO (OID_RECORRENCIA_TRANSACAO, OID_RECORRENCIA, ID_PARCELA,
                                             TPO_MOTIVO_EXCLUSAO, TPO_STATUS, COD_FIM_A_FIM, NUM_VALOR,
                                             FLG_NOTIFICACAO_DIA_ANTERIOR, INFORMACOES_ENTRE_USUARIOS,
                                             ID_CONCILIACAO_RECEBEDOR, DAT_TRANSACAO, DAT_EXCLUSAO)
VALUES (5, 2, 'e0a755bf-e1ed-4221-96b2-587b3a442a65', null, 'PENDENTE', 'E9999900420250211105433kyYIqAeRb', 10.00, 'S',
        null, null, SYSDATE, null);

INSERT INTO SPI_OWNER.RECORRENCIA_TRANSACAO (OID_RECORRENCIA_TRANSACAO, OID_RECORRENCIA, ID_PARCELA,
                                             TPO_MOTIVO_EXCLUSAO, TPO_STATUS, COD_FIM_A_FIM, NUM_VALOR,
                                             FLG_NOTIFICACAO_DIA_ANTERIOR, INFORMACOES_ENTRE_USUARIOS,
                                             ID_CONCILIACAO_RECEBEDOR, DAT_TRANSACAO, DAT_EXCLUSAO)
VALUES (6, 2, '7a9ea699-28fe-47cf-bc7a-caa9a26c8602', null, 'CRIADO', null, 10.00, 'N',
        null, null, ADD_MONTHS(SYSDATE, 1), null);

INSERT INTO SPI_OWNER.RECORRENCIA_TRANSACAO (OID_RECORRENCIA_TRANSACAO, OID_RECORRENCIA, ID_PARCELA,
                                             TPO_MOTIVO_EXCLUSAO, TPO_STATUS, COD_FIM_A_FIM, NUM_VALOR,
                                             FLG_NOTIFICACAO_DIA_ANTERIOR, INFORMACOES_ENTRE_USUARIOS,
                                             ID_CONCILIACAO_RECEBEDOR, DAT_TRANSACAO, DAT_EXCLUSAO)
VALUES (7, 2, '03915772-9f06-4738-9a91-24432db7df4f', null, 'CRIADO', null, 10.00, 'N',
        null, null, ADD_MONTHS(SYSDATE, 2), null);